import '@fontsource/noto-color-emoji/400.css';
import '@fontsource/noto-color-emoji/emoji-400.css';
import '@fontsource/noto-color-emoji/emoji.css';
import '@fontsource/roboto-mono/300-italic.css';
import '@fontsource/roboto-mono/300.css';
import '@fontsource/roboto-mono/400-italic.css';
import '@fontsource/roboto-mono/400.css';
import '@fontsource/roboto-mono/500-italic.css';
import '@fontsource/roboto-mono/500.css';
import '@fontsource/roboto-mono/700-italic.css';
import '@fontsource/roboto-mono/700.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { buildStoryParams, StoryDecorator } from '../packages/digital-net/packages/react-digital-ui';
import '../packages/digital-net/packages/react-digital-ui/assets/digital-net.default.css';
import '../assets/website.light.css';
import '../assets/website.dark.css';

export default buildStoryParams([StoryDecorator]);
